# Generated by Django 3.1.2 on 2020-10-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('experience', models.IntegerField(verbose_name='Опыт вождения')),
                ('driver_license', models.CharField(max_length=50, verbose_name='№ лиценции')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reg_log.client')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reg_log.client')),
                ('series', models.CharField(max_length=50, verbose_name='Серия')),
                ('identification_number', models.CharField(max_length=50, verbose_name='Идентификационный номер')),
            ],
        ),
    ]
