# Generated by Django 3.1.2 on 2020-10-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='client',
            new_name='id_client',
        ),
    ]
