# Generated by Django 3.1.2 on 2020-11-03 19:22

from django.db import migrations, models
import reg_log.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0003_auto_20201031_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('id_client',)},
        ),
        migrations.AlterModelOptions(
            name='passport',
            options={'ordering': ('client',)},
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='driver_license',
            field=models.CharField(max_length=50, unique=True, verbose_name='№ лиценции'),
        ),
        migrations.AlterField(
            model_name='client',
            name='experience',
            field=models.IntegerField(validators=[reg_log.models.validate_date], verbose_name='Опыт вождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='identification_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серия'),
        ),
    ]
