# Generated by Django 3.1.2 on 2020-12-05 18:25

from django.db import migrations, models
import reg_log.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0005_auto_20201205_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=50, unique=True, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='experience',
            field=models.IntegerField(help_text='*Формат: от 2 до 49', validators=[reg_log.models.validate_date], verbose_name='Опыт вождения'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
