# Generated by Django 3.1.2 on 2020-12-06 15:21

from django.db import migrations, models
import reg_log.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_log', '0006_auto_20201205_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identification_number',
            field=models.CharField(default=1, max_length=14, unique=True, verbose_name='Идентификационный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='series',
            field=models.CharField(choices=[('АВ', 'АВ'), ('ВМ', 'ВМ'), ('НВ', 'НВ'), ('КН', 'КН'), ('МР', 'МР'), ('МС', 'МС'), ('КВ', 'КВ'), ('РР', 'РР')], default=1, max_length=2, verbose_name='Серия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='driver_license',
            field=models.CharField(max_length=8, unique=True, verbose_name='№ лицензии'),
        ),
        migrations.AlterField(
            model_name='client',
            name='experience',
            field=models.IntegerField(help_text='Формат: <em>от 2 до 49</em>.', validators=[reg_log.models.validate_date], verbose_name='Опыт вождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='third_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.DeleteModel(
            name='Passport',
        ),
    ]
