# Generated by Django 3.1.2 on 2020-11-04 16:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='driver_license',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='№ лиценции'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, null=True, validators=[accounts.models.validate_date], verbose_name='Опыт вождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
