# Generated by Django 3.1.2 on 2020-11-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201105_0113'),
        ('accounts', '0004_auto_20201105_0121'),
        ('accounts', '0004_auto_20201105_0115'),
    ]

    operations = [
    ]
