# Generated by Django 3.1.2 on 2020-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('date_of_issue', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('engine', models.FloatField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('consumption_per_100', models.FloatField(max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
