# Generated by Django 3.1.2 on 2020-10-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_road_accident_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='condition',
            field=models.BooleanField(default=True),
        ),
    ]
