# Generated by Django 3.1.2 on 2020-10-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201031_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road_accident',
            name='defect',
            field=models.TextField(verbose_name='Повреждения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='repair_description',
            field=models.TextField(verbose_name='Описание работ'),
        ),
    ]
