# Generated by Django 3.1.2 on 2020-11-03 19:22

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201103_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='consumption_per_100',
            field=models.FloatField(max_length=50, validators=[catalog.models.validate_even], verbose_name='Расход на 100 км'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='engine',
            field=models.FloatField(max_length=50, validators=[catalog.models.validate_even], verbose_name='Объём двигателя'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[catalog.models.validate_even], verbose_name='Цена в день'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_of_end',
            field=models.DateTimeField(verbose_name='Дата окончания ремонта'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_of_start',
            field=models.DateTimeField(verbose_name='Дата начала ремонта'),
        ),
    ]
