# Generated by Django 3.1.2 on 2020-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201103_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='capacity',
            field=models.CharField(default=1, max_length=5, verbose_name='Багажник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.ImageField(default=1, upload_to='catalog/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель')], default=1, max_length=50, verbose_name='Топливо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='places',
            field=models.CharField(default=1, max_length=2, verbose_name='Места'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='power',
            field=models.CharField(default=1, max_length=4, verbose_name='Мощность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='reserve',
            field=models.CharField(default=1, max_length=5, verbose_name='Запас хода'),
            preserve_default=False,
        ),
    ]
