# Generated by Django 3.1.2 on 2020-12-04 13:09

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201204_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='body_type',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Универсал', 'Универсал'), ('Хэтчбэк', 'Хэтчбэк'), ('Купе', 'Купе'), ('Лифтбэк', 'Лифтбэк'), ('Внедорожник', 'Внедорожник'), ('Родстер', 'Родстер')], max_length=50, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Citroen', 'Citroen'), ('Ford', 'Ford'), ('Geely', 'Geely'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('LADA', 'LADA'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedec-Benz', 'Mercedec-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Skoda', 'Skoda'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=50, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='capacity',
            field=models.CharField(max_length=5, verbose_name='Багажник (л.)'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(choices=[('Красный', 'Красный'), ('Синий', 'Синий'), ('Чёрный', 'Чёрный'), ('Зеленый', 'Зеленый'), ('Серый', 'Серый'), ('Белый', 'Белый'), ('Оранжевый', 'Оранжевый'), ('Жёлтый', 'Жёлтый'), ('Коричневый', 'Коричневый')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='consumption_per_100',
            field=models.FloatField(max_length=50, validators=[catalog.models.validate_even], verbose_name='Расход (на 100 км.)'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='engine',
            field=models.FloatField(max_length=50, validators=[catalog.models.validate_even], verbose_name='Объём двигателя (л.)'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='fuel',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Гибрид', 'Гибрид')], max_length=50, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='number',
            field=models.CharField(max_length=5, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='places',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=2, verbose_name='Места'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='power',
            field=models.CharField(max_length=4, verbose_name='Мощность (л.с.)'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[catalog.models.validate_even], verbose_name='Цена в день (Br)'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='reserve',
            field=models.CharField(max_length=5, verbose_name='Запас хода (км.)'),
        ),
    ]
