# Generated by Django 3.1.2 on 2020-12-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201204_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road_accident',
            name='date_road_accident',
            field=models.DateField(verbose_name='Дата ДТП'),
        ),
    ]
